### ISSUE TITLE
soru

### ISSUE THREAD

**Issue by gHuseyinabi** [scrubjay55/Reddit-Tweet-Linker-Bot#1]
bu bot ne kadar güç harcıyor?(ram/işlemci vs.)

**Comment by scrubjay55** [comment]
multithreading kullandigima bakma. 1 cekirdek bile yeter. bu tarz scriptler cok resource harcamaz. herokuda calistiriyorum makinenin ozelliklerini bilmiyorum. bu tarz seyler icin de issue acmana gerek yok redditten dm atabilirsin ;) jdjdj
